In [1]:
import numpy as np

In [ ]:
arr = np.arange(1, 20)

In [ ]:
print(arr)

In [ ]:
print(arr + arr)np.random.randint(1, 100, 4

In [ ]:
print(arr - arr)

In [ ]:
print(arr*arr)

In [ ]:
print(arr + 100)
print()
print(arr - 100)
print()
print(arr * 100)
print()
print(arr / 100)

In [ ]:
1/0

In [ ]:
arr_zeros = np.zeros(10)

In [ ]:
arr_zeros

In [ ]:
arr_zeros / arr_zeros

In [ ]:
1 / arr_zeros

In [ ]:
arr ** 2

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr), arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [6]:
m1 = np.arange(0, 10).reshape(2, 5)
m2 = np.arange(0, 10).reshape(2, 5)

print(m1)
print(m2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
m1+m2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])